-- Burning Palms: bootstrap schema for Supabase (Postgres)
-- Generated by consolidating Prisma's existing SQLite migrations.
-- Run this ONCE in Supabase SQL Editor (Database -> SQL Editor).
--
-- Note: If you already created tables, this may error. In that case, either:
-- - run on a fresh database, or
-- - wrap statements in IF NOT EXISTS / adjust manually.

BEGIN;

-- Core auth + CMS tables
CREATE TABLE "User" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT,
  "email" TEXT NOT NULL,
  "emailVerified" TIMESTAMPTZ,
  "password" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'user',
  "image" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "Account" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "providerAccountId" TEXT NOT NULL,
  "refresh_token" TEXT,
  "access_token" TEXT,
  "expires_at" INTEGER,
  "token_type" TEXT,
  "scope" TEXT,
  "id_token" TEXT,
  "session_state" TEXT
);

CREATE TABLE "Session" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "sessionToken" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "expires" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "VerificationToken" (
  "identifier" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "expires" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "Page" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "content" TEXT NOT NULL DEFAULT '',
  "excerpt" TEXT,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "authorId" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL,
  "publishedAt" TIMESTAMPTZ,
  "settings" TEXT DEFAULT '{}'
);

CREATE TABLE "Post" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "content" TEXT NOT NULL DEFAULT '',
  "excerpt" TEXT,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "authorId" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL,
  "publishedAt" TIMESTAMPTZ
);

CREATE TABLE "Setting" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "type" TEXT NOT NULL DEFAULT 'string',
  "category" TEXT,
  "updatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "Media" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "filename" TEXT NOT NULL,
  "originalName" TEXT NOT NULL,
  "mimeType" TEXT NOT NULL,
  "size" INTEGER NOT NULL,
  "url" TEXT NOT NULL,
  "alt" TEXT,
  "uploadedById" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Menus
CREATE TABLE "Menu" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "location" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "MenuItem" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "menuId" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  "parentId" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL
);

-- Footer widgets
CREATE TABLE "FooterWidget" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "columnIndex" INTEGER NOT NULL,
  "title" TEXT,
  "type" TEXT NOT NULL DEFAULT 'links',
  "content" TEXT,
  "order" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL
);

-- Sidebar widgets
CREATE TABLE "SidebarWidget" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "title" TEXT,
  "type" TEXT NOT NULL DEFAULT 'links',
  "content" TEXT,
  "order" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL
);

-- Page builder sections
CREATE TABLE "PageSection" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "pageId" TEXT,
  "type" TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  "settings" TEXT,
  "content" TEXT,
  "visible" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL
);

-- Constraints (FKs)
ALTER TABLE "Account"
  ADD CONSTRAINT "Account_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User" ("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Session"
  ADD CONSTRAINT "Session_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User" ("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Page"
  ADD CONSTRAINT "Page_authorId_fkey"
  FOREIGN KEY ("authorId") REFERENCES "User" ("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Post"
  ADD CONSTRAINT "Post_authorId_fkey"
  FOREIGN KEY ("authorId") REFERENCES "User" ("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Media"
  ADD CONSTRAINT "Media_uploadedById_fkey"
  FOREIGN KEY ("uploadedById") REFERENCES "User" ("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "MenuItem"
  ADD CONSTRAINT "MenuItem_menuId_fkey"
  FOREIGN KEY ("menuId") REFERENCES "Menu" ("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "MenuItem"
  ADD CONSTRAINT "MenuItem_parentId_fkey"
  FOREIGN KEY ("parentId") REFERENCES "MenuItem" ("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- Indexes
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

CREATE INDEX "Account_userId_idx" ON "Account"("userId");
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");

CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

CREATE UNIQUE INDEX "Page_slug_key" ON "Page"("slug");
CREATE INDEX "Page_slug_idx" ON "Page"("slug");
CREATE INDEX "Page_status_idx" ON "Page"("status");

CREATE UNIQUE INDEX "Post_slug_key" ON "Post"("slug");
CREATE INDEX "Post_slug_idx" ON "Post"("slug");
CREATE INDEX "Post_status_idx" ON "Post"("status");

CREATE UNIQUE INDEX "Setting_key_key" ON "Setting"("key");
CREATE INDEX "Setting_key_idx" ON "Setting"("key");
CREATE INDEX "Setting_category_idx" ON "Setting"("category");

CREATE INDEX "Media_uploadedById_idx" ON "Media"("uploadedById");

CREATE INDEX "Menu_location_idx" ON "Menu"("location");
CREATE INDEX "MenuItem_menuId_idx" ON "MenuItem"("menuId");
CREATE INDEX "MenuItem_parentId_idx" ON "MenuItem"("parentId");
CREATE INDEX "MenuItem_order_idx" ON "MenuItem"("order");

CREATE INDEX "FooterWidget_columnIndex_idx" ON "FooterWidget"("columnIndex");
CREATE INDEX "FooterWidget_order_idx" ON "FooterWidget"("order");

CREATE INDEX "SidebarWidget_order_idx" ON "SidebarWidget"("order");

CREATE INDEX "PageSection_pageId_idx" ON "PageSection"("pageId");
CREATE INDEX "PageSection_order_idx" ON "PageSection"("order");
CREATE INDEX "PageSection_type_idx" ON "PageSection"("type");

COMMIT;

